volumes:
  pg_data:
  static:
  media:

services:
  postgres_db:
    container_name: store_db
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./store/
    container_name: store_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/
    depends_on:
      - postgres_db
  
  nginx:
    build: ./nginx/
    container_name: store_nginx
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/app/media/
    ports:
      - ${PORT}:80
    depends_on:
      - backend