global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'postgresql'
    static_configs:
      - targets: ['store_postgres_exporter:9187']
        labels:
          alias: postgres
  
  - job_name: 'nginx'
    static_configs:
      - targets: ['store_nginx-exporter:9113']