global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scheme: https
    metrics_path: '/prometheus/metrics'
    tls_config:
      ca_file: /prometheus/certs/server.crt
    basic_auth:
      username: PROMETHEUS_USERNAME
      password: PROMETHEUS_PASSWORD

  - job_name: 'postgresql'
    static_configs:
      - targets: ['store_postgres_exporter:9187']
        labels:
          alias: postgres
  
  - job_name: 'nginx'
    static_configs:
      - targets: ['store_nginx-exporter:9113']
  
  - job_name: 'django'
    static_configs:
      - targets: ['backend:8888']
    metrics_path: '/prometheus/metrics'